_target_: torch.nn.Sequential
_args_:
  - _target_: torch.nn.Linear
    in_features: 10
    out_features: 10
  - _target_: torch.nn.Relu
  - _target_: torch.nn.Linear
    out_dim: 10
  - _target_: torch.nn.Relu
  - _target_: torch.nn.Linear
    out_dim: 10
  - _target_: torch.nn.Relu
  - _target_: torch.nn.Linear
    out_dim: ${output_dim}
